# Generated by Django 3.0.7 on 2020-07-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
